# Make it use C-a, similar to screen..
unbind C-b
unbind l
set -g prefix C-a
bind-key C-a last-window

bind r source-file ~/.tmux.conf
set -g history-limit 200
set -g base-index 1
setw -g mode-keys vi
set-option -g history-limit 3000

# 垂直分割視窗
unbind u
bind v split-window -h
bind | split-window -h

# 水平分割視窗
bind h split-window -v
bind - split-window -v
bind -r M-Up resize-pane -U 5
bind -r M-Down resize-pane -D 5
bind -r M-Left resize-pane -L 5
bind -r M-Right resize-pane -R 5

bind-key -n F1 select-window -t 1
bind-key -n F2 select-window -t 2
bind-key -n F3 select-window -t 3
bind-key -n F4 select-window -t 4
bind-key -n F5 select-window -t 5
bind-key -n F6 select-window -t 6
bind-key -n F7 select-window -t 7
bind-key -n F8 select-window -t 8
bind-key -n F9 select-window -t 9
bind-key -n F10 select-window -t 10
bind-key -n F11 select-window -t 11
bind-key -n F12 select-window -t 12

# 256 colors please
set -g default-terminal "screen-256color"

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# fixes the delay problem
set -sg escape-time 0

# Enable mouse to pair with WezTerm
set -g mouse on

if-shell 'test "$(uname)" != "Darwin"' 'source ~/.tmux.conf.source'
if-shell 'test "$(uname)" = "Darwin"' 'source ~/.tmux.conf.source.osx'

if-shell "if [[ -x /usr/local/bin/reattach-to-user-namespace ]]; then true; else false; fi" "set-option -g default-command 'reattach-to-user-namespace -l $SHELL'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'egel/tmux-gruvbox'
#set -g @tmux-gruvbox 'dark' # or 'light'
set -g @plugin 'catppuccin/tmux#v2.1.3'
# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
